apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-jtot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-jtot
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-jtot
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-jtot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-jtot
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dshq-tenant/rhtap-demo-app/hacbs-test-project-jtot@sha256:bee809896bfc303f5703619ad009b1f5e65e25ab08e51de909c8422bd0df8dc6
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
