apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-jtot
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dshq-tenant/rhtap-demo-app/hacbs-test-project-jtot@sha256:96bf3499de0a8a08bad474f2ad965fe7699509197f2e12a7e1a51bfa2ee601d4
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
